spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/trace_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
